// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeText(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function DownloadVideo(arg1:string):Promise<Record<string, any>>;

export function ExtractAudio(arg1:string):Promise<Record<string, any>>;

export function GetAppVersion():Promise<string>;

export function GetFFmpegStatus():Promise<Record<string, any>>;

export function GetSettings():Promise<Record<string, any>>;

export function GetTaskStatus(arg1:string):Promise<Record<string, any>>;

export function Log(arg1:string):Promise<void>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:string):Promise<string>;

export function ParseVideo(arg1:string):Promise<Record<string, any>>;

export function RewriteText(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Record<string, any>>;

export function SaveFile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SaveSettings(arg1:Record<string, any>):Promise<void>;

export function SemanticSegment(arg1:string,arg2:string):Promise<Record<string, any>>;

export function TranscribeAudio(arg1:string,arg2:string):Promise<Record<string, any>>;
