// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeText(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyzeText'](arg1, arg2, arg3);
}

export function DownloadVideo(arg1) {
  return window['go']['main']['App']['DownloadVideo'](arg1);
}

export function ExtractAudio(arg1) {
  return window['go']['main']['App']['ExtractAudio'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetFFmpegStatus() {
  return window['go']['main']['App']['GetFFmpegStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTaskStatus(arg1) {
  return window['go']['main']['App']['GetTaskStatus'](arg1);
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function ParseVideo(arg1) {
  return window['go']['main']['App']['ParseVideo'](arg1);
}

export function RewriteText(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RewriteText'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SemanticSegment(arg1, arg2) {
  return window['go']['main']['App']['SemanticSegment'](arg1, arg2);
}

export function TranscribeAudio(arg1, arg2) {
  return window['go']['main']['App']['TranscribeAudio'](arg1, arg2);
}
