// This file is automatically generated. DO NOT EDIT

export interface VideoInfo {
  title?: string;
  author?: string;
  video_id?: string;
  cover_url?: string;
}

export interface DownloadResult {
  video_path?: string;
  filename?: string;
}

export interface AudioResult {
  audio_path?: string;
  filename?: string;
}

export interface TranscriptionResult {
  text?: string;
  language?: string;
  duration?: number;
}

export interface Segment {
  title?: string;
  content?: string;
}

export interface SegmentResult {
  segments?: Segment[];
}

export interface FFmpegStatus {
  installed?: boolean;
  path?: string;
}

export interface Task {
  id?: string;
  status?: string;
  progress?: number;
  message?: string;
  error?: string;
  result?: any;
}

export interface Settings {
  silicon_flow_key?: string;
  minimax_key?: string;
  download_dir?: string;
}

export interface ApiResponse<T = any> {
  code: number;
  message?: string;
  task_id?: string;
  data?: T;
}

// @ts-ignore
const wails = window.wails;

export async function GetFFmpegStatus(): Promise<FFmpegStatus> {
  return await wails.Invoke("GetFFmpegStatus");
}

export async function GetSettings(): Promise<Settings> {
  return await wails.Invoke("GetSettings");
}

export async function SaveSettings(settings: Settings): Promise<void> {
  return await wails.Invoke("SaveSettings", settings);
}

export async function ParseVideo(url: string): Promise<ApiResponse> {
  return await wails.Invoke("ParseVideo", url);
}

export async function DownloadVideo(url: string): Promise<ApiResponse> {
  return await wails.Invoke("DownloadVideo", url);
}

export async function ExtractAudio(videoPath: string): Promise<ApiResponse> {
  return await wails.Invoke("ExtractAudio", videoPath);
}

export async function GetTaskStatus(taskId: string): Promise<Task> {
  return await wails.Invoke("GetTaskStatus", taskId);
}

export async function TranscribeAudio(audioPath: string, apiKey?: string): Promise<ApiResponse> {
  return await wails.Invoke("TranscribeAudio", audioPath, apiKey);
}

export async function SemanticSegment(text: string, apiKey?: string): Promise<ApiResponse> {
  return await wails.Invoke("SemanticSegment", text, apiKey);
}

export async function AnalyzeText(text: string, apiKey?: string, provider?: string): Promise<ApiResponse> {
  return await wails.Invoke("AnalyzeText", text, apiKey, provider);
}

export async function RewriteText(text: string, apiKey?: string, provider?: string, style?: string, customInstruction?: string): Promise<ApiResponse> {
  return await wails.Invoke("RewriteText", text, apiKey, provider, style, customInstruction);
}

export async function SaveFile(content: string, filename: string): Promise<ApiResponse<{ path: string }>> {
  return await wails.Invoke("SaveFile", content, filename);
}

export async function OpenFileDialog(title: string, filter: string): Promise<string> {
  return await wails.Invoke("OpenFileDialog", title, filter);
}

export async function OpenDirectoryDialog(title: string): Promise<string> {
  return await wails.Invoke("OpenDirectoryDialog", title);
}

export async function GetAppVersion(): Promise<string> {
  return await wails.Invoke("GetAppVersion");
}

export async function Log(message: string): Promise<void> {
  return await wails.Invoke("Log", message);
}
